Repository python-wheel-build/fromager, pull requests merged in 2024-08, with the labels that each got.

#282 Enforce MyPy type checks, ignore files with known issues
  .github/workflows/check.yaml
  pyproject.toml
  src/fromager/external_commands.py
  src/fromager/vendor_rust.py
  tests/test_constraints.py
  tests/test_overrides.py
  tests/test_sdist.py
  tests/test_sources.py
  tox.ini
Labels: ci

#253 Generating CLI documentation
  .github/workflows/check.yaml
  .gitignore
  .readthedocs.yaml
  docs/Makefile
  docs/_static/.gitkeep
  docs/cli.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  tox.ini
Labels: ci

#284 feat: source finders should be aware of download config settings
  docs/customization.md
  src/fromager/commands/step.py
  src/fromager/finders.py
  src/fromager/sdist.py
  src/fromager/settings.py
  src/fromager/sources.py
  tests/test_finders.py
  tests/test_settings.py
  tests/test_sources.py
Labels: ci

#290 fix filenames in tarballs for sdists
  src/fromager/sources.py
  src/fromager/tarballs.py
  tests/test_tarballs.py
Labels: ci

#291 improve network isolation error handling
  src/fromager/external_commands.py
  tests/test_external_commands.py
Labels: ci

#293 rendering .md using myst-parser
  docs/conf.py
  docs/customization.md
  docs/index.rst
  docs/requirements.txt
Labels: documentation

#262 bug fix: warning for old patches
  src/fromager/overrides.py
  src/fromager/sources.py
  tests/test_overrides.py
  tests/test_sources.py
Labels: ci

#299 improve constraints file output
  src/fromager/commands/__init__.py
  src/fromager/commands/bootstrap.py
  src/fromager/commands/build_order.py
  src/fromager/commands/graph.py
  src/fromager/context.py
  src/fromager/sdist.py
  tests/test_bootstrap.py
Labels: bug, ci

#308 fix: use external_commands.run to apply patch
  e2e/flit_core_patches/flit_core/flit_core.patch
  e2e/test_override.sh
  src/fromager/external_commands.py
  src/fromager/sources.py
  tests/test_external_commands.py
Labels: ci

#309 fix: expose `default_patch_source` and return `is_new`
  src/fromager/sources.py
Labels: enhancement

#307 feat: add new `build_dir` field in settings
  docs/customization.md
  pyproject.toml
  src/fromager/dependencies.py
  src/fromager/settings.py
  src/fromager/sources.py
  src/fromager/wheels.py
  tests/test_settings.py
Labels: ci

#311 add a log message emphasizing build skip settings
  e2e/test_build_order.sh
  src/fromager/commands/build.py
Labels: ci

#312 support env files not tied to a variant
  docs/customization.md
  src/fromager/overrides.py
  tests/test_overrides.py
Labels: ci

#313 remove "why" information from build-order files
  src/fromager/commands/build_order.py
  src/fromager/context.py
  src/fromager/sdist.py
  tests/test_context.py
Labels: ci

#289 show plugin package and version
  e2e/flit_core_override/pyproject.toml
  e2e/test_override.sh
  src/fromager/overrides.py
  tests/test_overrides.py
Labels: ci

#320 feat: add changelog field to settings
  src/fromager/settings.py
  tests/test_settings.py
Labels: ci

#314 add package-specific settings files
  docs/customization.md
  src/fromager/__main__.py
  src/fromager/settings.py
  tests/test_settings.py
Labels: ci

#327 cleanup: remove example_override.py
  pyproject.toml
  src/fromager/example_override.py
  tests/test_finders.py
Labels: ci

#326 Drop support for Python 3.10
  .github/workflows/test.yaml
  .mergify.yml
  e2e/flit_core_override/pyproject.toml
  e2e/post_build_hook/pyproject.toml
  e2e/stevedore_override/pyproject.toml
  pyproject.toml
Labels: ci, mergify

#330 pass constraints file when installing build dependencies
  e2e/test_build.sh
  e2e/test_report_missing_dependency.sh
  e2e/test_rust_vendor.sh
  src/fromager/__main__.py
  src/fromager/context.py
  src/fromager/sdist.py
  src/fromager/wheels.py
  tests/conftest.py
  tests/test_context.py
  tests/test_sdist.py
Labels: ci

#335 download multiple packages in parallel in download-sequence
  e2e/test_download_sequence.sh
  src/fromager/commands/download_sequence.py
Labels: enhancement, ci

#329 feat: add extra metadata files while building wheels
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_extra_metadata.sh
  requirements.txt
  src/fromager/wheels.py
Labels: ci, mergify

#336 enable CI on macos
  .github/workflows/test.yaml
  .mergify.yml
  e2e/mergify_lint.py
  e2e/test_rust_vendor.sh
Labels: ci, mergify

#341 upload logs on e2e failures to help debug
  .github/workflows/test.yaml
Labels: ci

#342 fix artifact naming conflicts
  .github/workflows/test.yaml
Labels: ci

#325 feat: add build tags to built wheels
  .github/workflows/test.yaml
  .mergify.yml
  e2e/changelog_settings.yaml
  e2e/test_bootstrap.sh
  e2e/test_bootstrap_build_tags.sh
  e2e/test_build.sh
  e2e/test_build_order.sh
  e2e/test_build_settings.sh
  e2e/test_extra_metadata.sh
  e2e/test_meson.sh
  e2e/test_override.sh
  e2e/test_prebuilt_wheels_alt_server.sh
  e2e/test_rust_vendor.sh
  src/fromager/candidate.py
  src/fromager/commands/build.py
  src/fromager/finders.py
  src/fromager/resolver.py
  src/fromager/sdist.py
  src/fromager/settings.py
  src/fromager/wheels.py
  tests/test_finders.py
  tests/test_resolver.py
  tests/test_settings.py
Labels: ci, mergify

#349 macOS: Run unit tests and less e2e tests
  .github/workflows/test.yaml
  .mergify.yml
  e2e/mergify_lint.py
  tox.ini
Labels: ci, mergify

#352 feat: add global changelog to trigger rebuilds of all packages with new build tag
  src/fromager/commands/build.py
  src/fromager/sdist.py
  src/fromager/settings.py
  src/fromager/wheels.py
  tests/test_settings.py
Labels: ci

#348 Improve coverage reporting
  .github/workflows/test.yaml
  .gitignore
  e2e/common.sh
  pyproject.toml
  requirements-test.txt
  tests/test_dependencies.py
  tox.ini
Labels: ci

#345 Include ELF requirements and provides in dist-info
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_elfdeps.sh
  requirements.txt
  src/fromager/wheels.py
Labels: ci, mergify

#354 Pydantic model for global and package settings
  e2e/build_settings.yaml
  requirements.txt
  src/fromager/commands/__init__.py
  src/fromager/commands/migrate_config.py
  src/fromager/packagesettings.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_packagesettings.py
  tests/testdata/config-0.27/envs/cpu/torch.env
  tests/testdata/config-0.27/envs/torch.env
  tests/testdata/config-0.27/expected/torch.yaml
  tests/testdata/config-0.27/settings.yaml
  tests/testdata/context/overrides/patches/test_other_pkg-1.0.0/001-mypatch.patch
  tests/testdata/context/overrides/patches/test_pkg-1.0.2/001-somepatch.patch
  tests/testdata/context/overrides/patches/test_pkg-1.0.2/002-otherpatch.patch
  tests/testdata/context/overrides/settings.yaml
  tests/testdata/context/overrides/settings/test_empty_pkg.yaml
  tests/testdata/context/overrides/settings/test_pkg.yaml
Labels: ci

#363 fix: change req_type from string to enum
  src/fromager/commands/bootstrap.py
  src/fromager/context.py
  src/fromager/requirements_file.py
  src/fromager/sdist.py
  tests/test_bootstrap.py
  tests/test_sdist.py
Labels: ci

#362 feat: create a new graph module
  .github/workflows/test.yaml
  .mergify.yml
  e2e/migrate_graph/old_constraints.txt
  e2e/migrate_graph/old_graph.json
  e2e/test_migrate_graph.sh
  src/fromager/commands/bootstrap.py
  src/fromager/commands/graph.py
  src/fromager/context.py
  src/fromager/dependency_graph.py
  src/fromager/sdist.py
  tests/test_bootstrap.py
  tests/test_graph.py
Labels: ci, mergify

#323 Define Pydantic model for package config
  docs/customization.md
  e2e/build_settings.yaml
  e2e/build_settings/stevedore.yaml
  e2e/changelog_settings-2/stevedore.yaml
  e2e/changelog_settings.yaml
  e2e/changelog_settings/stevedore.yaml
  e2e/test_bootstrap.sh
  e2e/test_bootstrap_build_tags.sh
  e2e/test_build_order.sh
  e2e/test_build_settings.sh
  e2e/test_extra_metadata.sh
  e2e/test_prebuilt_wheels_alt_server.sh
  src/fromager/__main__.py
  src/fromager/commands/__init__.py
  src/fromager/commands/bootstrap.py
  src/fromager/commands/build.py
  src/fromager/commands/list_overrides.py
  src/fromager/commands/migrate_config.py
  src/fromager/context.py
  src/fromager/dependencies.py
  src/fromager/finders.py
  src/fromager/overrides.py
  src/fromager/packagesettings.py
  src/fromager/sdist.py
  src/fromager/settings.py
  src/fromager/sources.py
  src/fromager/wheels.py
  tests/conftest.py
  tests/test_context.py
  tests/test_overrides.py
  tests/test_packagesettings.py
  tests/test_settings.py
  tests/test_sources.py
  tests/testdata/context/overrides/settings.yaml
Labels: ci

#375 cleanup: move wheels related functions from sdist to wheels module
  src/fromager/commands/build.py
  src/fromager/commands/download_sequence.py
  src/fromager/sdist.py
  src/fromager/wheels.py
  tests/test_sdist.py
  tests/test_wheels.py
Labels: ci
