Repository python-wheel-build/fromager, pull requests merged in 2024-06, with the labels that each got.

#17 add markdownlint action
  .github/workflows/check.yaml
Labels: ci

#18 require markdownlint to work
  .mergify.yml
Labels: mergify

#19 configure markdownlint
  .github/workflows/check.yaml
  .markdownlint-cli2.yaml
  .markdownlint-config.yaml
  .mergify.yml
  docs/develop.md
Labels: ci, mergify

#22 require bootstrap job
  .mergify.yml
Labels: mergify

#23 add e2e bootstrap job
  .github/workflows/test.yaml
  .gitignore
  e2e/test_bootstrap.sh
  e2e/test_without_isolation.sh
Labels: ci

#26 switch rules for e2e jobs to use pending parameterized names
  .mergify.yml
Labels: mergify

#24 end-to-end test for reporting a missing dependency
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_report_missing_dependency.sh
  src/fromager/sdist.py
Labels: ci, mergify

#28 set up pkglint
  .github/workflows/check.yaml
  .gitignore
  .mergify.yml
  pyproject.toml
  tox.ini
Labels: ci, mergify

#31 make the pkglint job use the right python version
  .github/workflows/check.yaml
Labels: ci

#35 add e2e test showing that rebuilds work
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_build_with_build_order.sh
Labels: ci, mergify

#36 set up automated publishing
  .github/workflows/python-publish.yaml
  pyproject.toml
  tox.ini
Labels: ci

#43 tox: set base_python to 3.11 for most envs
  tox.ini
Labels: ci

#44 e2e: change port for local wheel server
  e2e/test_build_with_build_order.sh
  e2e/test_report_missing_dependency.sh
Labels: ci

#45 Test on Python 3.10 for Intel Gaudi
  .github/workflows/test.yaml
  .mergify.yml
  e2e/flit_core_override/pyproject.toml
  pyproject.toml
Labels: ci, mergify

#47 feature: write a constraints.txt file next to build-order.json
  e2e/test_bootstrap.sh
  src/fromager/context.py
Labels: ci

#46 bootstrap: record the URL of the source package downloaded
  e2e/test_report_missing_dependency.sh
  src/fromager/__main__.py
  src/fromager/context.py
  src/fromager/sdist.py
  src/fromager/sources.py
  tests/test_context.py
Labels: ci

#53 feature: log the output of the build command
  e2e/test_bootstrap.sh
  e2e/test_build_with_build_order.sh
  src/fromager/wheels.py
Labels: ci

#49 Vendor Rust crates into source distributions
  .github/workflows/test.yaml
  .gitignore
  e2e/pyo3_test/Cargo.lock
  e2e/pyo3_test/Cargo.toml
  e2e/pyo3_test/MANIFEST.in
  e2e/pyo3_test/pyproject.toml
  e2e/pyo3_test/python/pyo3_test/__init__.py
  e2e/pyo3_test/rust/lib.rs
  e2e/pyo3_test/tests.py
  e2e/pyo3_test/tox.ini
  pyproject.toml
  src/fromager/dependencies.py
  src/fromager/vendor_rust.py
  src/fromager/wheels.py
Labels: ci

#56 update the mergify rules to account for python 3.10 and rust 1.75
  .mergify.yml
Labels: mergify

#55 convert cli processing to use click
  README.md
  e2e/test_build_with_build_order.sh
  e2e/test_report_missing_dependency.sh
  pyproject.toml
  src/fromager/__main__.py
  src/fromager/commands/__init__.py
  src/fromager/commands/bootstrap.py
  src/fromager/commands/build_order.py
  src/fromager/commands/canonicalize.py
  src/fromager/commands/step.py
  tests/test_bootstrap.py
  tests/test_main.py
Labels: ci

#58 rename build_with_build_order to build_steps
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_build_steps.sh
Labels: ci, mergify

#59 feature: add a command for building one wheel
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_build.sh
  src/fromager/commands/__init__.py
  src/fromager/commands/build.py
Labels: ci, mergify

#61 feature: add a build-sequence command
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_build_order.sh
  src/fromager/commands/__init__.py
  src/fromager/commands/build.py
Labels: ci, mergify

#62 force new entries in mergify and github actions when we write e2e scripts
  e2e/mergify_lint.py
  tox.ini
Labels: ci

#63 integrate rust vendoring with source preparation
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_rust_vendor.sh
  src/fromager/sources.py
  src/fromager/vendor_rust.py
Labels: ci, mergify

#77 feature: prefer our wheel server over pypi.org for prebuilt wheels
  .github/workflows/test.yaml
  .mergify.yml
  e2e/test_prebuilt_wheels_alt_server.sh
  src/fromager/sdist.py
  src/fromager/sources.py
Labels: ci, mergify

#80 add dependabot config
  .github/dependabot.yml
Labels: ci

#85 adding download sequence command
  .github/workflows/test.yaml
  .mergify.yml
  e2e/download_sequence/simplejson-build-order.json
  e2e/test_download_sequence.sh
  src/fromager/commands/__init__.py
  src/fromager/commands/download_sequence.py
Labels: ci, mergify

#88 let the resolver filter the type of distribution
  .gitignore
  pyproject.toml
  src/fromager/resolver.py
  src/fromager/sdist.py
  src/fromager/sources.py
  tests/test_resolver.py
  tests/test_sdist.py
Labels: ci

#89 configure mergify for code reviews
  .mergify.yml
Labels: mergify

#91 require 1 approver
  .mergify.yml
Labels: mergify

#97 make e2e jobs more robust
  e2e/test_bootstrap.sh
  e2e/test_build_order.sh
  e2e/test_build_steps.sh
Labels: ci

#93 when bootstrapping, report origin of each requirement
  src/fromager/commands/bootstrap.py
  tests/test_bootstrap.py
Labels: ci

#100 Add Ruff for linting and auto-formatting
  pyproject.toml
  src/fromager/__main__.py
  src/fromager/commands/__init__.py
  src/fromager/commands/bootstrap.py
  src/fromager/commands/build.py
  src/fromager/commands/build_order.py
  src/fromager/commands/canonicalize.py
  src/fromager/commands/download_sequence.py
  src/fromager/commands/step.py
  src/fromager/context.py
  src/fromager/dependencies.py
  src/fromager/example_override.py
  src/fromager/external_commands.py
  src/fromager/extras_provider.py
  src/fromager/finders.py
  src/fromager/overrides.py
  src/fromager/resolver.py
  src/fromager/sdist.py
  src/fromager/server.py
  src/fromager/settings.py
  src/fromager/sources.py
  src/fromager/vendor_rust.py
  src/fromager/wheels.py
  tests/conftest.py
  tests/test_bootstrap.py
  tests/test_context.py
  tests/test_dependencies.py
  tests/test_external_commands.py
  tests/test_finders.py
  tests/test_resolver.py
  tests/test_sdist.py
  tests/test_settings.py
  tox.ini
Labels: ci

#98 feature: make a new sdist after running prepare_source
  README.md
  e2e/run_all.sh
  e2e/test_bootstrap.sh
  e2e/test_build_steps.sh
  pyproject.toml
  src/fromager/commands/build.py
  src/fromager/commands/step.py
  src/fromager/context.py
  src/fromager/dependencies.py
  src/fromager/sdist.py
  src/fromager/sources.py
  src/fromager/tarballs.py
  tests/test_tarballs.py
Labels: ci
